config/routes.rb
Rails.application.routes.draw do
  
  def constraint(req)
    return req.path.scan(/\/rails\/active_storage.+/).empty?
  end
  
  get 'about', to: 'about#show'
  get 'albums', to: 'albums#show'
  get 'albums/submit'
  get 'albums/fetch', to: 'albums#fetch'
  post 'albums/update', to: 'albums#update'
  post 'albums/create'
  post 'albums/destroy'
  
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  post 'reports/create'
  post 'reports/destroy'

  get 'panel', to: 'users#panel'
  get 'users/resend-email', to: 'users#resend_confirmation_email'
  get 'users/:username', to: 'users#show', as: 'user', constraints: { :username => /[^\/]+/ }
  post 'users/destroy'
  post 'users/create'
  post 'users/update'
  #post 'users/toggle-admin', to: 'users#toggle_admin'
  #post 'users/toggle-ban', to: 'users#toggle_ban'
  get 'users/:id/confirm-email', to: 'users#confirm_email'
  get 'users/:reset_password_token/reset-password', to: 'users#password_reset'
  post 'users/:reset_password_token/reset-password', to: 'users#password_update'
  post 'users/password-reset', to: 'users#send_password_reset_email'
  
  #Helper tools - MUST BE REMOVED IN PROD!!!
  get 'tools/make-admin', to: 'users#make_admin'
  get 'tools/nuke-admin', to: 'users#nuke_admin'
  
  get 'forum', to: 'forum#show'
  get 'forum/:category', to: 'forum#show_board', as: 'category'
  get 'forum/*category/t/:thread_id', to: 'forum_threads#show', as: 'thread', constraints: lambda { |request| constraint(request) }
  
  get 'thread/:category/new', to: 'forum_threads#new', as: 'board'
  post 'thread/destroy', to: 'forum_threads#destroy'
  post 'thread/create', to: 'forum_threads#create'
  post 'thread/toggle-pinned', to: 'forum_threads#toggle_pinned'
  
  post 'posts/create'
  post 'posts/update'
  post 'posts/destroy'

  post 'upvotes/create'
  
  get 'articles', to: 'articles#show'
  get 'articles/new'
  get 'articles/:article_id', to: 'articles#show_article', as: 'article', constraints: lambda { |request| constraint(request) }
  post 'articles/create'
  post 'articles/update'
  post 'articles/destroy'
  post 'articles/toggle-featured', to: 'articles#toggle_featured'
  
  post 'comments/create'
  post 'comments/destroy'
  
  post 'subscriptions/create'
  post 'subscriptions/destroy'
  
  post 'notifications/mark-as-read', to: 'notifications#mark_as_read'
  
  get 'home', to: 'home#show'
  
  post 'announcements/create'
  post 'announcements/destroy'
  
  resources :albums
  
  get '*unmatched_route', to: 'application#render_404', constraints: lambda { |request| constraint(request) }
  root 'home#show'
end

app/views/partials/_login.html.erb
<form enctype="multipart/form-data" action="<%= root_url %>login" accept-charset="UTF-8" data-remote="true" method="post">
    <input placeholder="Username" type="text" name="session[username]">
    <input placeholder="Password" type="password" name="session[password]">
    <input value="Login" type="submit" name="commit">
</form>
<div id="login-links">
    <a class="register-btn">Create an account</a>
    <a class="password-reset-btn">Forgot password?</a>
</div>

app/views/partials/_logout.html.erb
<div>
	<p>Currently logged in as <i><%= fetch_user.username %></i></p>
	<div id="profile-nav">
		<a href="<%= root_url + 'users/' + fetch_user.username.downcase %>"><ion-icon name="md-person" title="Profile"></ion-icon></a>
		<% if Notification.where(user: fetch_user, unread: true).present? %>
		<a id="notification-btn" class="unread-notifications"><ion-icon name="ios-mail-unread" title="Notifications"></ion-icon></a>
		<% else %>
		<a id="notification-btn"><ion-icon name="ios-mail" title="Notifications"></ion-icon></a>
		<% end %>
		<% if fetch_user.admin %>
		<a href="<%= root_url + 'panel' %>"><ion-icon name="ios-settings" title="Panel"></ion-icon></a>
		<% end %>
	</div>
	<a id="logout-btn" rel="nofollow" data-method="delete" href="<%= root_url + 'logout' %>"><ion-icon name="ios-log-out" title="Log out"></ion-icon></a>
	<div id="notification-list" class="hidden">
		<h3>Recent notifications:</h3>
		<% @notifications = Notification.where(user: fetch_user, unread: true).order('created_at').reverse_order.limit(5) %>
		<% if !@notifications.present? %>
		<i>No unread notifications!</i>
		<% else %>
			<% @notifications.each do | n | %>
				<% if n.notification_type == 'ForumThread' %>
				<% @post = Post.find_by(id: n.target_id) %>
				<% @thread = @post.forum_thread %>
				<a class="notification-card" href="<%= forum_path + "/#{@thread.category}/t/#{@thread.id}" %>">
					<div class="notification-header">
						<h4><%= @post.user.username %> posted in <%= @thread.title %>:</h4>
						<p>Posted <%= @post.created_at.strftime('%b %d') %></p>
					</div>
					<div class="notification-divider"></div>
					<div class="notification-body">
						<p><%= parse_markdown(@post.body.split(/\n/)[0], true) %></p>
					</div>
				</a>
				<% elsif n.notification_type == 'Article' %>
				<% @comment = Comment.find_by(id: n.target_id) %>
				<% @article = @comment.article %>
				<a class="notification-card" href="<%= articles_path + "/#{@article.id}" %>">
					<div class="notification-header">
						<h4><%= @comment.user.username %> commented on <%= @article.title %>:</h4>
						<p>Posted <%= @comment.created_at.strftime('%b %d') %></p>
					</div>
					<div class="notification-divider"></div>
					<div class="notification-body">
						<p><%= parse_markdown(@comment.body.split(/\n/)[0], true) %></p>
					</div>
				</a>
				<% end %>
			<% end %>
		<% end %>
		<a id="see-all" href="<%= root_url + 'users/' + fetch_user.username.downcase %>">See all</a>
	</div>
</div>

app/views/partials/_navbar_slim.html.erb
<nav id="sidebar">
    <ul id="nav-list">
        <li>
            <%= link_to "Home", root_url %>
            <%= link_to "Articles", articles_path %>
            <%= link_to "Forum", forum_path %>
            <%= link_to "Archive", albums_path %>
            <%= link_to "Submit", albums_submit_path %>
            <%= link_to "About / FAQ", about_path %>
        </li>
    </ul>
</nav>